language: java

sudo: true

jdk:
  - oraclejdk8

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y dos2unix
 - find ./src/test/ -name '*.txt' | xargs unix2dos
 - chmod +x gradlew

script:
- ./gradlew check

addons:
  apt:
    packages:
      - oracle-java8-installer